# Generated by Django 5.2.3 on 2025-06-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedfile',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='trackedfile',
            name='current_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
