# Generated by Django 5.2.3 on 2025-06-14 08:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_trackedfile_uploaded_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedfile',
            name='current_content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
